### ISSUE TITLE
[QUESTION] How i can use differnt colors?

### ISSUE THREAD

**Issue by stormenergy91** [yeqown/go-qrcode#112]
How i can realize a qrcode like this one: 

![Schermata del 2024-06-13 11-50-56](https://github.com/yeqown/go-qrcode/assets/103607470/4c836cda-d9e0-4920-9c63-a0cc48453ae8)

If is not possible, how i can use different colors for the 3 big angle squares (or cicles) and the inside elements? 

Tanks

**Comment by yeqown** [comment]
not support yet
