### ISSUE TITLE
WithCustomShape 该如何使用

### ISSUE THREAD

**Issue by fanshuai** [yeqown/go-qrcode#19]
- 虽然支持WithCustomShape，但IShape.Draw依赖DrawContext，但DrawContext中的变量全部为私有，自定义后无法读取相关变量，定位像素点位置。
- 请问是否有相关示例可参考，如将WithCircleShape中的圆半径缩小至80%。

**Comment by yeqown** [comment]
@fanshuai https://github.com/yeqown/go-qrcode/pull/20/files 我把其中的变量暴露出来了，同时也提供了一个example；我在example 尝试实现缩小 80% 圆半径，但是很奇怪无法被识别，我可能要花一点时间确定下原因，你现在可以在 feature/with-custom-shape 这个分支尝试一下，欢迎交流

**Comment by fanshuai** [comment]
@yeqown 太效率了，非常感谢，我这边今天有尝试改源码，80%可以识别，75%不行；稍后会再试试你的示例，有结论会及时在这跟你反馈 ~

**Comment by yeqown** [comment]
@fanshuai 应该是finder的形状，导致二维码无法识别，我屏蔽了finder部分使用自定义形状，然后我尝试了0.7大小是可以的。

**Comment by fanshuai** [comment]
👍👍 好使，感谢，问题已解决 ~

**Comment by fanshuai** [comment]
![IMG_4563](https://user-images.githubusercontent.com/1005487/118385052-38141580-b63e-11eb-9c91-dcf7cec3d9c7.JPG)

- 参考企业微信，右下角的识别坐标是否也需要设置为 matrix.StateFinder？（FYI: qrcode.go:363）
