### ISSUE TITLE
go panic when using single character string

### ISSUE THREAD

**Issue by borislavone** [yeqown/go-qrcode#28]
`_, err := qrcode.New("a")`
`if err != nil {`
`    log.Fatal(err)`
`}`
2021/07/05 16:43:46 encodeAlphanumericCharacter() with non alphanumeric char a
panic: encodeAlphanumericCharacter() with non alphanumeric char a

goroutine 1 [running]:
log.Panicf(0x6bd5c8, 0x3b, 0xc00010fb20, 0x1, 0x1)
        C:/Users/storm/dev/go/src/log/log.go:361 +0xc7
github.com/yeqown/go-qrcode.encodeAlphanumericCharacter(0xc000048561, 0xc000014180)
        C:/Users/storm/go/pkg/mod/github.com/yeqown/go-qrcode@v1.5.5/encoder.go:266 +0x110
github.com/yeqown/go-qrcode.(*encoder).encodeAlphanumeric(0xc000120000)
        C:/Users/storm/go/pkg/mod/github.com/yeqown/go-qrcode@v1.5.5/encoder.go:146 +0x54
github.com/yeqown/go-qrcode.(*encoder).Encode(0xc000120000, 0xc0000140f8, 0x1, 0x8, 0x40, 0x2030000, 0x2030000)
        C:/Users/storm/go/pkg/mod/github.com/yeqown/go-qrcode@v1.5.5/encoder.go:100 +0x18d
github.com/yeqown/go-qrcode.(*QRCode).dataEncoding(0xc00011e000, 0xc000120000, 0x15, 0xc00000aae0, 0x1, 0x8)
        C:/Users/storm/go/pkg/mod/github.com/yeqown/go-qrcode@v1.5.5/qrcode.go:173 +0x74
github.com/yeqown/go-qrcode.(*QRCode).init(0xc00011e000, 0xc00011e000, 0xc000006088)
        C:/Users/storm/go/pkg/mod/github.com/yeqown/go-qrcode@v1.5.5/qrcode.go:128 +0x305
github.com/yeqown/go-qrcode.New(0x6b2f3a, 0x1, 0xc00010ff68, 0x1, 0x1, 0x595acb, 0xc000046058, 0x5a9801)
        C:/Users/storm/go/pkg/mod/github.com/yeqown/go-qrcode@v1.5.5/qrcode.go:40 +0x1e5
main.main()
        C:/Users/storm/projects/go/qrcbug/main.go:10 +0x7d

**Comment by yeqown** [comment]
got it, thanks for your feedback

**Comment by yeqown** [comment]
@borislavone this was fixed in `v1.5.6`
