### ISSUE TITLE
Quality?

### ISSUE THREAD

**Issue by orefalo** [yeqown/go-qrcode#31]
Hi, neat project

Is there a setting to control QA parameters?

**Comment by yeqown** [comment]
Could you describe it detailly? `Quality` means `QR Code` quality or `project code`  quality?

**Comment by orefalo** [comment]
Sorry for not being clear.

I meant QR code quality settings. Which, let me use the right jargon, is called the "error correction level"
   https://www.thonky.com/qr-code-tutorial/character-capacities

If I may ask a few more questions:

Same question regarding the mode, is there a way to force the mode?

I assume the version [1-40] is picked automatically.

So far so good, I coupled your project with https://github.com/makiuchi-d/gozxing and it works like a charm for my automatic testing.

great project.
Thank you so much,

**Comment by yeqown** [comment]
Here was a PR https://github.com/yeqown/go-qrcode/pull/27 of this, but it was not designed with appropriate APIs. I don't want to throw away the guy's work，so I'm still waiting for his improvement ~

**Comment by orefalo** [comment]
Good, thanks for the pointer.
When you say "was not designed with appropriate APIs" ; what would be your expectation?

**Comment by yeqown** [comment]
Working in progress #32

**Comment by yeqown** [comment]
@orefalo I create a PR #33 adds some optimize：

- `outputEncodingOptions` is not exportable type: alias it as `Config`
-  chore: README, Makefile, Testcase

**Comment by orefalo** [comment]
tks for merging in @yeqown 

will test the new PR#33 on my experiment project -> https://github.com/orefalo/signedqrcode

**Comment by orefalo** [comment]
I will close this issue as PR#33 solves it all and exposes the proper API.

Thank you
