### ISSUE TITLE
Borderless QRCode

### ISSUE THREAD

**Issue by arajhansa** [yeqown/go-qrcode#34]
How can I generate a QRcode jpeg buffer without QRcode having borders?

I want to generate something like this:
![sample_qr_code](https://user-images.githubusercontent.com/30975477/128838581-1a06549f-317e-49a3-89fc-3bbc2e1aaa81.jpg)

**Comment by yeqown** [comment]
it's not optional yet 😄, let me open a feature iteration

**Comment by yeqown** [comment]
all changes are committed in #35 @arajhansa, sample would like this:

```go
New("source text", WithBorderWidth(0))
// WithBorderWidth accept varargs[0-4+], 0 means default border width, 1 means all use this parameter, 
// 2+ means top/bottom use the firset, left/right use the second
// 4+ means top, right, bottom, left is specifed in the order.
```

this feature is not version tagged, so you may need to try this on feature branch.

**Comment by arajhansa** [comment]
Looks awesome. Thanks a lot @yeqown
