### ISSUE TITLE
Saving QR to file for the second time gives different (corrupted) output

### ISSUE THREAD

**Issue by hubertat** [yeqown/go-qrcode#40]
When I create a QR code (doesn't matter is it with option, custom shape etc) and save it to file two (or more) times only 1st output is correct. Second (and third) output file is corrupted - few 'pixels' near finder areas are different.

Sample code:
```
	plainQr, err := qrcode.New("https://github.com/")
	if err != nil {
		panic(err)
	}
	err = plainQr.Save("./out1.png")
	if err != nil {
		log.Println(err)
	}
	err = plainQr.Save("./out2.png")
	if err != nil {
		log.Println(err)
	}
```

QR code `out1.png` reads OK, `out2.png` doesn't read at all.

You may ask why I'm saving same QR for the second time 😄 I'm doing custom multi colour codes and need to obtain width and height of the QR code - found this as solution: generate it for the first time to save maxH and maxW in my custom-shape object, then generate it for the second time to produce my coloured QR.

**Comment by yeqown** [comment]
Let me check this issue

**Comment by yeqown** [comment]
that's a bug, this library must support save QR Code image one more time and only generated once. By the way, do you need the size of QR code image? Should I support APIs to expose such attributes like `width`, `height`, `padding`? @hubertat

**Comment by yeqown** [comment]
In my implementation, I fill the matrix of QR Code, then I draw it into images, the size is determinate after drawing it. So I have no idea about how to expose those attributes before you called `Save` and it-like functions yet.

**Comment by yeqown** [comment]
Fixed it in #41, you can try it with branch [issue-40/could-not-save-one-more-times](https://github.com/yeqown/go-qrcode/tree/issue-40/could-not-save-one-more-times)

**Comment by hubertat** [comment]
Hi, @yeqown tried new version: my issue is fixed! Thanks a lot! 🥇

**Comment by yeqown** [comment]
@hubertat there's a new API [Attribute](https://pkg.go.dev/github.com/yeqown/go-qrcode#QRCode.Attribute) for QRCode to help you get the size of the generated image, maybe provide helpful in your case?

**Comment by hubertat** [comment]
Yes! Already tried and using Attribute :) Thank you!

**Comment by yeqown** [comment]
my pleasure 😉
