### ISSUE TITLE
Save (stream) to []byte

### ISSUE THREAD

**Issue by BuckeyeCoder** [yeqown/go-qrcode#50]
**Thank you for this library.** I have it working just fine in PNG file mode.

I would like to save the image to a `[]byte` and not save it to disk. Can you provide an example of how to create your own `Writer` to do this?

I attempted to use `newWriter` but its not exposed (private function). I tried to implement a `Write()` method but this requires knowledge about `matrix.Matrix` which is quite QR code technical.

I have a hunch there is an easier way but I don't see it. Perhaps a new `StreamWriter` in addition to the provided `Standard` and `Terminal` writers would be just as easy as writing an example here? I'd be happy to contribute once I see the path forward.

**Comment by yeqown** [comment]
got it, give me some minutes to check this

**Comment by yeqown** [comment]
@BuckeyeCoder  Actually, the standard has been designed as `StreamWriter`, it provides `New` (save into file by default) and `NewWithWriter` (to specify yourself `io.WriterColoser`). Maybe what you want is:

```go
type bufferAdaptor struct {
	*bytes.Buffer
}

func (b bufferAdaptor) Close() error {
	return nil
}

func (b bufferAdaptor) Write(p []byte) (int, error) {
	return b.Buffer.Write(p)
}

func main() {
	b := bufferAdaptor{Buffer: bytes.NewBuffer(nil)}
	w := standard.NewWithWriter(b)
	_ = w
}
```

**Comment by BuckeyeCoder** [comment]
**Thank you.** Let me study this for a bit and I'll get back with you here.
