### ISSUE TITLE
Example for how to encode []byte

### ISSUE THREAD

**Issue by BuckeyeCoder** [yeqown/go-qrcode#56]
Hello again @yeqown  :grin: 

I am doing more testing and have a question. Suppose I have some binary data in a `[]byte` like this:

```
someBinaryDataToEncode := []byte{8, 48, 37, 237, 187, 89, 0}
```
Since `qrcode.New()` and `qrcode.NewWith()` takes `string` type for the input, how can we encode this `byte` data? I see `qrcode.sourceRawBytes` on the `struct` but it is private and I do not see a public `func` to populate it. 

If you could help me, I can write something up for `/example` folder. Thank you @yeqown

**Comment by BuckeyeCoder** [comment]
@yeqown The more I thought about it I just decided to add the ability to use io.Reader because there are many use cases for reading from a file and byte.Buffer as well. 

This does not break the API because it is all new. 

I was careful to use your style with respect to calling the private `build()` function. 

The tests, both new and existing, all pass. I hope you like the new ability! :smile:

**Comment by yeqown** [comment]
let's discuss this in PR, I'd like to try this feature and review `Encoding Definition in QR specification.
