### ISSUE TITLE
cannot install package on go 1.12 because of math.MaxInt

### ISSUE THREAD

**Issue by eeddaann** [yeqown/go-qrcode#58]
I couldn't install the package on vscode with go 1.12. got the following error message:
```
go get -u github.com/yeqown/go-qrcode
# github.com/yeqown/go-qrcode
..\..\go\src\github.com\yeqown\go-qrcode\mask_evaluation.go:35:10: undefined: math.MaxInt
..\..\go\src\github.com\yeqown\go-qrcode\mask_evaluation.go:113:10: undefined: math.MaxInt
..\..\go\src\github.com\yeqown\go-qrcode\mask_evaluation.go:148:10: undefined: math.MaxInt
```
I guess the problem is similar to the bug which described here:
https://github.com/buger/goterm/commit/b630d372aa7a528c355c2e6b456ad583fd488967

**Comment by yeqown** [comment]
MR is accepted, but upgrading the go version maybe help you follow the community better 😬 ~
