### ISSUE TITLE
QR WithLogoImage behaviour - expected or bug?

### ISSUE THREAD

**Issue by hubertat** [yeqown/go-qrcode#65]
Hi @yeqown, question regarding QR with logo inside: when I create one, it seems that the logo image just covers inner part of QR code, the inner/center part is not empty and then logo image is put on it.
Is that expected behaviour?

I guess the error correction makes that OK, but still, in my opinion it would be better if QR code would be generated with keeping that space empty (and having all the information not in this center area) and putting logo there.

BTW I was really glad seeing v2 coming, I really like your work!
Hubert

**Comment by yeqown** [comment]
Yes, it was designed to be this.

Actually, it could not work as you thought, the QR Code's generation and hatch both have their spec. If you changed the patch rule, the QR Code scanner could not work with it. Maybe you mean skipping filling the part which would be covered by icon image, but it has no difference with it is now.

However, it does not mean that we don't have any way to change it, I'm learning **_QArt QR Code_** recently, There may be some similarities between your opinion and it. I hope it could provides some inspiration to us.
