### ISSUE TITLE
Why is jpeg is used by default?

### ISSUE THREAD

**Issue by stokito** [yeqown/go-qrcode#68]
The jpg format is a loosing compression and was developed for photos. But for qr codes the ideal format is PNG and resulting files are about 10 times smaller.
Could you please switch the defaults to PNG?

Because now I started working a big project that generates thousands of QR codes daily. Each of them about 23-25kb and uploaded to S3 buckets. This is just gigantic waste of money and bandwidth.
I'll change all this but wondered how this might happen in first place.
And now I see that even in the sample in README the output format is JPEG.

Also please add an example of resizing the resulted image. Because I see in code that my colleges just resizing the generated QR code. But I guess the minimal qr must be generated by default wit only a pixel for a dot. And latter if it can be resized by a browser or app itself on view

**Comment by yeqown** [comment]
#69 related, we call to discuss in that issue, so this closed.

**Comment by stokito** [comment]
the issue is more about changing documentation

**Comment by stokito** [comment]
It would be even cooler to change default to PNG. But this may break existing dependents.
At least README must be updated for sure. I've spent some time to figure out how to use PNG instead of JPEG
