### ISSUE TITLE
How can I find which version is for Go 1.16?

### ISSUE THREAD

**Issue by kazekim** [yeqown/go-qrcode#80]
With some SSL issues, I cannot upgrade to use latest golang version. I still strict with go 1.16. In this case, How can I find which go-qrcode version that I can use with go 1.16?

Thank you

**Comment by yeqown** [comment]
This repository upgrade go version from `1.13` to `1.17` in this commit https://github.com/yeqown/go-qrcode/commit/ef83c8ac1d12b275e023a4a3a21d60b3de51196b .So you can use `git tag --merged ef83c8ac1d12b275e023a4a3a21d60b3de51196b` It would look like:
```bash
v1.0
v1.0.0
...
v1.5.7
v1.5.8
```
You can get the version which is the most suitable for you.

**Comment by kazekim** [comment]
Thank you @yeqown
