### ISSUE TITLE
编译二进制 qrcode 失败

### ISSUE THREAD

**Issue by xgfone** [yeqown/go-qrcode#82]
进入 `github.com/yeqown/go-qrcode/cmd/qrcode`，然后执行 `go build` 进行编译时，报错了，提示
```
main module (github.com/yeqown/go-qrcode/v2) does not contain package github.com/yeqown/go-qrcode/v2/cmd/qrcode
```

把 `qrcode` 目录拷贝到其它非 `go-qrcode` 目录（以及子目录）下，就没问题了。

**Comment by yeqown** [comment]
Normally, we want you to install the CLI application as the following command:

```bash
go install github.com/yeqown/go-qrcode/cmd/qrcode@latest
```

Of course, now you can retry this after pulling the latest codes.

**Comment by xgfone** [comment]
问题仍然存在。

我尝试了更新了一下 `cmd/qrcode/go.mod`：
- `github.com/yeqown/go-qrcode/v2` 从 `v2.2.0` 更新到 `v2.2.1`。
- `github.com/yeqown/go-qrcode/writer/standard` 从 `v1.2.0` 更新到 `v1.2.1`。

然后，就可以正常编译了。
