### ISSUE TITLE
制作出来的二维码图片比较大

### ISSUE THREAD

**Issue by xgfone** [yeqown/go-qrcode#83]
使用 [`python-qrcode`](https://github.com/lincolnloop/python-qrcode) 制作出来的二维码图片只有 **702** 个字节，但使用本项目 `go-qrcode` 制作出来的二维码图片却有 **13298** 个字节，大小相差了将近 19 倍。有什么办法缩小二维码尺寸大小吗？

**说明：** 使用相同的文本，其它配置几乎一样（或者都按默认配置）。

**Comment by yeqown** [comment]
There is a similar issue  https://github.com/yeqown/go-qrcode/issues/69, which has been fixed.

**Comment by yeqown** [comment]
If you really care about the generated size of the QR Code image, try this writer(https://github.com/yeqown/go-qrcode/tree/main/writer/compressed) instead. Of course, it would lose some features(colorful)
