### ISSUE TITLE
[BUG] Terminal writer not working on MacOS.

### ISSUE THREAD

**Issue by brunoga** [yeqown/go-qrcode#94]
**Describe the bug**
Running the use-terminal-writer example results in nothing being printed to the Terminal at all.

**To Reproduce**
Just run the example, it shows nothing.

**Expected behavior**
I was expecting to see a text mode version of the QRCode showing up in the terminal.

**Screenshots**
N/A as the result is nothing is printed.

**Additional context**
N/A

**Comment by brunoga** [comment]
BTW, I just tested in Linux and it also did not work.

**Comment by yeqown** [comment]
Thanks for your feedback, I'll follow it up

**Comment by yeqown** [comment]
@brunoga would you like to test the fixup code at #95 ?

**Comment by yeqown** [comment]
terminal v1.1.1 has been released
