### ISSUE TITLE
[BUG] Transparent background

### ISSUE THREAD

**Issue by EhabSalah** [yeqown/go-qrcode#99]
**Describe the bug**
standard.WithBgTransparent() doesn't set the background as transparent!

**To Reproduce**
customWriter := &customWriteCloser{}
standard.NewWithWriter(
		customWriter,
		standard.WithBgTransparent(),
	)

**Expected behavior**
Black foreground with transparent background image
**Screenshots**
<img width="549" alt="image" src="https://github.com/yeqown/go-qrcode/assets/24505720/253743fe-37ae-49b5-b8c6-75f3b627e681">

**Comment by localpurpose** [comment]
set the .png extension bro

**Comment by yeqown** [comment]
@EhabSalah Could you provide the minimal code sample that reproduces the bug? As the @localpurpose said are you using PNG format to output?

**Comment by Nadim147c** [comment]
Hi, I'm facing the the same issue. My code:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/spf13/pflag"
	"github.com/yeqown/go-qrcode/v2"
	"github.com/yeqown/go-qrcode/writer/standard"
	"github.com/yeqown/go-qrcode/writer/standard/shapes"
)

var (
	fg  = "#222222"
	out = "qrcode.png"
)

func main() {
	pflag.StringVarP(&fg, "foreground", "f", fg, "foreground color")
	pflag.StringVarP(&out, "output", "o", out, "output file name")
	pflag.Parse()

	log.SetFlags(0)
	if pflag.NArg() != 1 {
		fmt.Fprint(os.Stderr, "USE:\n    pretty-qr-enc [--flags] <text to encode>\n\n")
		log.Fatal("please provide a text to encode")
	}

	shape := shapes.Assemble(shapes.RoundedFinder(), shapes.SquareBlocks(1))

	qrc, err := qrcode.New(pflag.Arg(0))
	if err != nil {
		log.Fatal(err)
	}

	w, err := standard.New(out,
		standard.WithBgTransparent(),
		standard.WithFgColorRGBHex(fg),
		standard.WithBorderWidth(0),
		standard.WithCustomShape(shape),
	)
	if err != nil {
		log.Fatal(err)
	}

	err = qrc.Save(w)
	if err != nil {
		log.Fatal(err)
	}
}
```
---
### The issue

The issue is that the`New` and `NewWithWriter` does not check for the extension and use the default encoder. The default encoder is `jpeg`. So, even though the file name is `<name>.png`, the encoding in jpeg. 

```bash
$ file qrcode.png
qrcode.png: JPEG image data, baseline, precision 8, 420x420, components 3
```
